name: Deploy to Workshop

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "main"
      - uses: gmod-workshop/workshop-upload@v1.1.0
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          vdf: ${{ secrets.STEAM_VDF }}
          id: ${{ secrets.ADDON_ID }}
          markdown-changelog: ${{ github.event.release.body }}
          folder: ./
